### ISSUE TITLE
Add bpmnProcessId to VariableRecord

### ISSUE THREAD

**Issue by Benjoyo** [camunda-community-hub/zeebe-exporter-protobuf#188]
Since 1.4.0-alpha2, zeebe includes the bpmnProcessId in the VariableRecord during export:

https://github.com/camunda/zeebe/issues/8181

Could you please also add this field here? Thanks.

**Comment by saig0** [comment]
@Benjoyo thank you for raising this up :+1: 

Feel free to contribute a PR :rocket:  As an example, you could look into #177.

**Comment by saig0** [comment]
Done by #232.
