### ISSUE TITLE
Missing ValueType mappings

### ISSUE THREAD

**Issue by jamulv** [camunda-community-hub/zeebe-exporter-protobuf#309]
The following `ValueType` mappings are missing vs camunda (based on enum comparison):
```
PROCESS_INSTANCE_RESULT
FORM
PROCESS_INSTANCE_BATCH
MESSAGE_BATCH
```
Additionally the following types are defined but missing encoding in `RecordTransformer`
```
RESOURCE_DELETION
ESCALATION
COMMAND_DISTRIBUTION
```
Worth adding tests to check the alignment!

Finally it would be good to have something to encode mapping errors (if a type were missing a message should still be encoded to describe the missing mapping)

**Comment by saig0** [comment]
@jamulv thank you for raising it. :+1: 

Currently, the schema depends on Zeebe 8.2. Adding the new value type is a required step for updating it to Zeebe 8.3. The missing record types can be implemented step-by-step. 

Feel free to contribute. :rocket: 

> Finally it would be good to have something to encode mapping errors (if a type were missing a message should still be encoded to describe the missing mapping)

The handling of mapping errors depends on the usage of the schema. 

Where/how do you use the schema?
