### ISSUE TITLE
Update to protobuf version 4.x is not compatible with older 3.x version used in other parts of Zeebe

### ISSUE THREAD

**Issue by VonDerBeck** [camunda-community-hub/zeebe-exporter-protobuf#366]
Thanks a lot for updating this exporter especially with the important UserTask events and all the other Zeebe 8.5 details. I really appreciate that 👍 

Sadly the upgrade to google-protobuf version 4.x causes incompatibilities with the older 3.x version included in the current 8.5.1 versions of zeebe-client-java, zeebe-gateway-protocol-impl, etc. 
I get exceptions like `java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3` if using this exporter library together with other parts of Zeebe.

See PR #365 for a fix.

**Comment by saig0** [comment]
@VonDerBeck thank you for raising it. :+1: 

There is no strong need to update the Protobuf version now. Let's downgrade the version to align with Camunda 8.5.
